# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='serial_no',
            field=models.CharField(default='3ee37f', help_text='Simpler unique identifier for this user', max_length=6, unique=True),
        ),
    ]
