# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_basicinfo_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='contact_number',
            field=models.CharField(blank=True, help_text='The contact number of the user', max_length=10),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='serial_no',
            field=models.CharField(default='143cd0', help_text='Simpler unique identifier for this user', max_length=6, unique=True),
        ),
    ]
