# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20170223_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='group',
        ),
    ]
