# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20170307_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyinfo',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='curriculum.Subject'),
        ),
    ]
