# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user_management', '0003_remove_basicinfo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
