# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20170213_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='serial_no',
            field=models.CharField(default='a8f250', help_text='Simpler unique identifier for this user', max_length=6, unique=True),
        ),
    ]
