# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_basicinfo_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course'),
        ),
        migrations.AlterField(
            model_name='facultyinfo',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='curriculum.Subject'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Semester'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
