# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20170213_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='BasicInfo',
        ),
    ]
