# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_course_semester_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
