# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20170223_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationrequest',
            name='request_date',
            field=models.DateField(default=datetime.date(2017, 2, 23)),
        ),
    ]
