# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_facultyinfo_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectfaculty',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='subjectfaculty',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='subjectfaculty',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='facultyinfo',
            name='course',
        ),
        migrations.DeleteModel(
            name='SubjectFaculty',
        ),
    ]
