# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0006_auto_20170214_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': set([('can_write_university_credits', 'can write university credits'), ('can_read_id_card_req', 'can read id card req'), ('can_read_exam_schedule', 'can read exam schedule'), ('can_read_university_credits', 'can read university credits'), ('can_write_meeting_details', 'can write meeting details'), ('can_read_bonafide_req', 'can read bonafide req'), ('can_write_pass_my_book', 'can write pass my book'), ('can_read_internal_assessment', 'can read internal assessent'), ('can_write_study_materials', 'can write study materials'), ('can_read_attendance', 'can read attendance'), ('can_read_activity_log', 'can read activity log'), ('can_write_fee_collections', 'can write fee collections'), ('can_write_exam_hall_plan', 'can write exam hall plan'), ('can_write_id_card_req', 'can write id card req'), ('can_write_fee_dues', 'can write fee dues'), ('can_write_attendance', 'can write attendance'), ('can_write_time_table', 'can write time table'), ('can_read_pass_my_book', 'can read pass my book'), ('can_read_online_discussion', 'can read online discussion'), ('can_read_rail_pass_req', 'can read rail pass req'), ('can_read_fee_collections', 'can read fee collections'), ('can_write_notices', 'can write notices'), ('can_write_internal_assessment', 'can write internal assessment'), ('can_read_library_card_req', 'can read library card req'), ('can_read_assignments', 'can read assignments'), ('can_write_online_discussion', 'can write online discussion'), ('can_read_time_table', 'can read time table'), ('can_write_activity_log', 'can write activity log'), ('can_write_assignments', 'can write assignments'), ('can_read_exam_hall_plan', 'can read exam hall plan'), ('can_write_rail_pass_req', 'can write rail pass req'), ('can_read_study_materials', 'can read study materials'), ('can_authenticate_users', 'can authenticate users'), ('can_write_exam_schedule', 'can write exam schedule'), ('can_write_library_card_req', 'can write library card req'), ('can_write_bonafide_req', 'can write bonafide req'), ('can_read_meeting_details', 'can read meeting details'), ('can_read_notices', 'can read notices'), ('can_read_main_page', 'can read main page'), ('can_write_personal_profile', 'can write personal profile'), ('can_read_fee_dues', 'can read fee dues')]),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='The contact number of the user', max_length=10)),
                ('serial_no', models.CharField(default='256d07', help_text='Simpler unique identifier for this user', max_length=6, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
