# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_studentinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
