# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20170224_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminInfo',
        ),
    ]
