# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.Semester'),
        ),
    ]
