# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20170214_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='serial_no',
            field=models.CharField(default='232df1', help_text='Simpler unique identifier for this user', max_length=6, unique=True),
        ),
    ]
