# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='minutes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting_details.MeetingMinute'),
        ),
    ]
