# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_details', '0004_auto_20170512_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date', '-time')},
        ),
        migrations.AlterModelOptions(
            name='meetingminute',
            options={'ordering': ('-time',)},
        ),
        migrations.AddField(
            model_name='meetingminute',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
