# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_details', '0005_auto_20170512_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
