# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_details', '0006_auto_20170512_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingminute',
            options={'ordering': ('time',)},
        ),
    ]
