# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0009_auto_20170307_2039'),
        ('curriculum', '0002_subject_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('max_credits', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subject')),
            ],
        ),
    ]
