# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20170307_2039'),
        ('university_credits', '0002_auto_20170318_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitycredit',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university_credits.SubjectCredit'),
        ),
        migrations.AddField(
            model_name='universitycredit',
            name='marks',
            field=models.IntegerField(default=0, help_text='Marks for that student in that subject'),
        ),
        migrations.AddField(
            model_name='universitycredit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo'),
        ),
    ]
