# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
