# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20170318_1328'),
        ('study_material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='course',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subject'),
        ),
    ]
