# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_marks', models.IntegerField(help_text='Maximum marks that can be allotted in a metric')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0, help_text='Marks for that student in that metric')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_assessment.Metric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Subject')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentmetric',
            unique_together=set([('student', 'subject', 'metric')]),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set([('subject', 'name', 'max_marks')]),
        ),
    ]
