# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('semester', 'day_of_week')]),
        ),
    ]
