# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('timetable', '0002_auto_20170303_0011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set([('semester', 'day_of_week', 'start_time')]),
        ),
    ]
