# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0009_auto_20170307_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('IDC', 'ID Card'), ('LBC', 'Library Card'), ('RSP', 'Railway Season Pass'), ('LBB', 'Library Book'), ('BFC', 'Bonafide Certificat')], help_text='Type of the document requested', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo')),
            ],
        ),
    ]
