# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo'),
        ),
    ]
