# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_auto_20170505_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_management.FeeCollection')),
            ],
        ),
    ]
