# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='pending_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='item_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
