# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0004_auto_20170506_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='fee_items',
            field=models.ManyToManyField(to='fee_management.FeeItem'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
