# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_subject_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('conductor', models.CharField(help_text='Name of the person that conducted the activity.', max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Semester')),
            ],
        ),
    ]
