# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0010_auto_20170302_2243'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.TimeTable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo')),
            ],
        ),
    ]
