# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.StudentInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('date', 'student', 'lecture')]),
        ),
    ]
