# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20170302_2243'),
        ('timetable', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('date', 'student', 'lecture')]),
        ),
    ]
