# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(help_text='Name of the examination', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Name or number of the room', max_length=200)),
                ('start_seat', models.IntegerField()),
                ('end_seat', models.IntegerField()),
                ('subjet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examinations.Exam')),
            ],
        ),
    ]
