# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_auto_20170323_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.PositiveIntegerField(default=2017, help_text='Year that the academic year started in.'),
        ),
    ]
