# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_auto_20170323_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomassignment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
