# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_auto_20170323_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examinations.Exam')),
            ],
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
