# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-11-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0008_auto_20180521_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.PositiveIntegerField(default=2019, help_text='Year that the academic year started in.'),
        ),
    ]
